---
name: Build & Test
"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: ["py38", "py39", "py310", "py311", "py312"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: |
            ${{
              matrix.env == 'py38'  && '3.8'  ||
              matrix.env == 'py39'  && '3.9'  ||
              matrix.env == 'py310' && '3.10' ||
              matrix.env == 'py311' && '3.11' ||
              '3.12'
            }}

      - run: python3 -m pip install --upgrade setuptools tox virtualenv
      - run: tox -e ${{ matrix.env }}
